algoritmo cofre

        inteiro q25, q10, q5
        real total

    início
        escreva "Entre com a quantidade de moedas de R$ 0,25"
        leia q25
        escreva "Entre com a quantidade de moedas de R$ 0,10"
        leia q10
        escreva "Entre com a quantidade de moedas de R$ 0,05"
        leia q5
        total = q25*0.25+q10*0.10+q5*0.05
        escreva "O valor total em reais é: R$" + total
    fim